### ISSUE TITLE
open from device 

### ISSUE THREAD

**Issue by ardorG-ai** [epam/mriviewer#155]
The function opened from the device does not work properly.

**Comment by ardorG-ai** [comment]
properties of undefined (reading 'click')
    at SmartContainer.onButtonOpenLocalFileClick (FileReader.js:635:1)
    at handler (SmartContainer.jsx:66:1)
    at HTMLUnknownElement.callCallback (react-dom.development.js:3945:1)
    at Object.invokeGuardedCallbackDev (react-dom.development.js:3994:1)
    at invokeGuardedCallback (react-dom.development.js:4056:1)
    at invokeGuardedCallbackAndCatchFirstError (react-dom.development.js:4070:1)
    at executeDispatch (react-dom.development.js:8243:1)
    at processDispatchQueueItemsInOrder (react-dom.development.js:8275:1)
    at processDispatchQueue (react-dom.development.js:8288:1)
    at dispatchEventsForPlugins (react-dom.development.js:8299:1)
    at react-dom.development.js:8508:1
    at batchedEventUpdates$1 (react-dom.development.js:22396:1)
    at batchedEventUpdates (react-dom.development.js:3745:1)
    at dispatchEventForPluginEventSystem (react-dom.development.js:8507:1)
    at attemptToDispatchEvent (react-dom.development.js:6005:1)
    at dispatchEvent (react-dom.development.js:5924:1)
    at unstable_runWithPriority (scheduler.development.js:468:1)
    at runWithPriority$1 (react-dom.development.js:11276:1)
    at discreteUpdates$1 (react-dom.development.js:22413:1)
    at discreteUpdates (react-dom.development.js:3756:1)
    at dispatchDiscreteEvent (react-dom.development.js:5889:1)

**Comment by DanilRostov** [comment]
Thanks for firing the issue @ardorG-ai.
We have created ticket for this and will let you know as soon as fixed.

**Comment by DanilRostov** [comment]
Dear @ardorG-ai, we have fixed issues related to hte file opening functionality in our recent release. Please try it out. In case you find other problems please feel free to create separate issue. Thank you.
